// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0Ai7PSk9uS22WvwMQxNukd1CfnpWdqZM',
    appId: '1:224615074525:web:655b6fb5f2d3d289e4a934',
    messagingSenderId: '224615074525',
    projectId: 'finanzas-yahir',
    authDomain: 'finanzas-yahir.firebaseapp.com',
    storageBucket: 'finanzas-yahir.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXt2GP1pmW78pA1FPW54Bo68ERnxQNbsM',
    appId: '1:224615074525:android:0557aee8f100f099e4a934',
    messagingSenderId: '224615074525',
    projectId: 'finanzas-yahir',
    storageBucket: 'finanzas-yahir.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhDUnTnNBt_z-4ApNNdPxkbAvhNoqv31E',
    appId: '1:224615074525:ios:c0671ae28ad8e376e4a934',
    messagingSenderId: '224615074525',
    projectId: 'finanzas-yahir',
    storageBucket: 'finanzas-yahir.appspot.com',
    iosBundleId: 'com.example.actividad02Yahirdegante',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhDUnTnNBt_z-4ApNNdPxkbAvhNoqv31E',
    appId: '1:224615074525:ios:c0671ae28ad8e376e4a934',
    messagingSenderId: '224615074525',
    projectId: 'finanzas-yahir',
    storageBucket: 'finanzas-yahir.appspot.com',
    iosBundleId: 'com.example.actividad02Yahirdegante',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0Ai7PSk9uS22WvwMQxNukd1CfnpWdqZM',
    appId: '1:224615074525:web:a6145f1fcda697a5e4a934',
    messagingSenderId: '224615074525',
    projectId: 'finanzas-yahir',
    authDomain: 'finanzas-yahir.firebaseapp.com',
    storageBucket: 'finanzas-yahir.appspot.com',
  );
}
